/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autos;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josen
 */
public class frmRegistros extends javax.swing.JFrame {

    Object datos2[]=new Object[3];
    registros cl = new registros();
    ResultSet rs = null;
    ResultSet rs2 = null;
    DefaultTableModel mdlregistro=new DefaultTableModel();
        
    public frmRegistros() {
       
       
        
        initComponents();
        this.setLocationRelativeTo(frmRegistros.this);
        this.setTitle("Registro de Automoviles");
//        LlenarTabla();


    mdlregistro.addColumn("id");
    mdlregistro.addColumn("Marca");
    mdlregistro.addColumn("Modelo");
    mdlregistro.addColumn("Tipo");
    mdlregistro.addColumn("color");
    mdlregistro.addColumn("precio");
    mdlregistro.addColumn("gasofa");

        rs = null;
        rs2 = null;
        
        rs = cl.buscarTodo();
        
        //mdlregistro.setRowCount(0);
        
        
        try {
             while (rs.next()) {
                
                 
                 
                String id=rs.getString(1);
                
               String marca= rs.getString(2);
                
               String modelo= rs.getString(3);
                String tipo = rs.getString(4);
                String color = rs.getString(5);
                String precio = rs.getString(6);
                String gasolina = rs.getString(7);
                rs2 = cl.buscartipo(tipo);
                 try {
                     while (rs2.next()) {
                         
                    String aux=(rs2.getString(2));
                        tipo=aux;
                        
                     }
                 } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "AVISO DEL SISTEMA", JOptionPane.ERROR_MESSAGE);
        }
              
                
                
                   tablaRegistro.setModel(mdlregistro);
                 Object datos[] = {id,marca,modelo,tipo,color,precio,gasolina};
                 
                 mdlregistro.addRow(datos);
                   tablaRegistro.setModel(mdlregistro);
                
             }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "AVISO DEL SISTEMA", JOptionPane.ERROR_MESSAGE);
        }
      

//hola
    }
    public void LlenarTabla() {
//        rs = null;
//        rs2 = null;
//        rs = cl.buscarTodo();
//        mdlregistro.setRowCount(0);
//        
//        try {
//             while (rs.next()) {
//                String id = rs.getString(1);
//                String marca = rs.getString(2);
//                String modelo = rs.getString(3);
//                String tipo = rs.getString(4);
//                String color = rs.getString(5);
//                String precio = rs.getString(6);
//                String gasolina = rs.getString(7);
//                rs2 = cl.buscartipo(tipo);
//                 try {
//                     while (rs2.next()) {
//                    String aux=(rs2.getString(2));
//                        tipo=aux;
//                     }
//                 } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "AVISO DEL SISTEMA", JOptionPane.ERROR_MESSAGE);
//        }
//                Object datos[] = {id, marca,modelo,tipo,color,precio,gasolina};
//                mdlregistro.addRow(datos);
//             }
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "AVISO DEL SISTEMA", JOptionPane.ERROR_MESSAGE);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRegistro = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaRegistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. Registro", "Marca", "Tipo", "Modelo", "Color", "Precio", "Combustible"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaRegistro);

        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(btnRegresar)
                .addGap(47, 47, 47)
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar)
                    .addComponent(btnSalir))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        setVisible(false);
       new  frmAutomoviles().setVisible(true);
        
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        String botones[]={"Cerrar","Cancelar"};
                int eleccion=JOptionPane.showOptionDialog(this,"¿desea cerrar la aplicacion?", "Advertencia", 0, 0, null, botones, this);
                if(eleccion==JOptionPane.YES_OPTION){
                    System.exit(0); 
                }
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tablaRegistro;
    // End of variables declaration//GEN-END:variables
}
